spring:
  application:
    name: dasiolmap

  # ai:
  #   openai:
  #     model: ${OPEN_AI_MODEL}
  #     api:
  #       key: ${OPEN_AI_KEY}
  #       url: ${OPEN_AI_URL}

  # # mariadb
  datasource:
    driver-class-name: ${DRIVER}
    url: ${URL}
    username: ${USER}
    password: ${PASSWD}

  # h2 db
  # datasource:
  #     driver-class-name:  org.h2.Driver
  #     # url: jdbc:h2:mem:inspire
  #     url: jdbc:h2:file:./data/inspire;AUTO_SERVER=TRUE
  #     username: root
  #     password:

  jpa:
    hibernate:
      # create, create-drop, update, none
      ddl-auto: update
      # 맨 처음 실행 시 create -> none
    # 콘솔출력
    show-sql: true
    properties:
      hibernate:
        # h2
        # dialect: org.hibernate.dialect.H2Dialect
        # mariadb
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console # http://localhost:8088/h2-console

server:
  port: 8088

# token
jwt:
  secret: "dasiolmap-super-secret-key-for-jwt-123456789"

# openApi:
#   serviceKey: ${SERVICE_KEY}
#   callBackUrl: ${CALLBACKURL}
#   dataType: ${TYPE}


mybatis: 
    mapper-locations: /mappers/**/*Mapper.xml
